# Taken from AuthMe's repo
# MIT
name: Release

# On changes to release branches
on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  publish_github:
    name: Publish to GitHub
    runs-on: ubuntu-latest

    steps:
      - name: ✨ Checkout repository
        uses: actions/checkout@v2

      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: 🐘 Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: 📢 Publish new release to GitHub
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 📦 Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.release.outputs.tag_name }}
          files: 'versions/*/build/libs/*'
          token: ${{ secrets.GITHUB_TOKEN }}

  publish_modrinth_curse:
    name: Publish
    runs-on: ubuntu-latest

    strategy:
      matrix:
        minecraft_version: ["1.18.2", "1.19.2", "1.19.3"]

    steps:
      - name: ✨ Checkout repository
        uses: actions/checkout@v2

      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: 🐘 Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build JAR
        run: ./gradlew :${{ matrix.minecraft_version }}-fabric:build

      - name: Publish (CurseForge/Modrinth)
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          curseforge-id: 754889
          curseforge-token: ${{secrets.CURSEFORGE_TOKEN}}

          modrinth-id: E6BMMeJm
          modrinth-token: ${{secrets.MODRINTH_TOKEN}}

          name: "Tubion ${{ github.ref }} for Minecraft ${{ matrix.minecraft_version }}"
          version: "${{ github.ref }}"
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: fabric
          game-versions: "${{ matrix.MINECRAFT_VERSION }}"
          java: "17"